#! /bin/sh

# Autostart
# ====
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom --experimental-backends &
feh --bg-fill ~/wallpapers/lucifer.jpg &
~/.config/polybar/launch.sh &

# xrandr --output HDMI-0 --left-of DP-0 --primary
xrandr --output DP-0 --primary --mode 1920x1080 --rotate normal --output HDMI-0 --mode 1920x1080 --rotate normal --left-of DP-0
bspc wm -O DP-0 HDMI-0

# Workspaces
# ====
bspc monitor DP-0 -d 0 1 2 3 4 5 6
bspc monitor HDMI-0 -d 7 8 9
# laptop
bspc monitor eDP-1 -d 0 1 2 3 4 5 6 7 8 9

# Custom
# ====
bspc config top_padding             0
bspc config border_width            2
bspc config window_gap              16
bspc config split_ratio             0.6
bspc config focused_border_color    "#4169e1"
