#! /bin/sh

# Autostart
# ====
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom --experimental-backends &
feh --bg-fill ~/Pictures/bg_01.jpg &
~/.config/polybar/launch.sh &
xrandr --output HDMI-0 --left-of DP-0

# Workspaces
# ====
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# Custom
# ====
bspc config top_padding             5
bspc config border_width            2
bspc config window_gap              16
bspc config split_ratio             0.6
bspc config focused_border_color     "#4169e1"
